/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Student = IDL.Record({
  'status' : IDL.Text,
  'topic' : IDL.Text,
  'name' : IDL.Text,
  'degreeType' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'externalLinks' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'address' : IDL.Text,
});
export const ProfessorProfile = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'institution' : IDL.Text,
  'name' : IDL.Text,
  'department' : IDL.Text,
  'location' : IDL.Text,
});
export const Publication = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Text,
  'year' : IDL.Nat,
  'publication' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateStudent' : IDL.Func([Student], [], []),
  'addResearchInterest' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getProfessorProfile' : IDL.Func([], [ProfessorProfile], ['query']),
  'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
  'getResearchInterests' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMaintenanceMode' : IDL.Func([], [IDL.Bool], ['query']),
  'removePublication' : IDL.Func([IDL.Text], [], []),
  'removeResearchInterest' : IDL.Func([IDL.Text], [], []),
  'removeStudent' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMaintenanceMode' : IDL.Func([IDL.Bool], [], []),
  'updatePublication' : IDL.Func([Publication], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Student = IDL.Record({
    'status' : IDL.Text,
    'topic' : IDL.Text,
    'name' : IDL.Text,
    'degreeType' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ContactInfo = IDL.Record({
    'externalLinks' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'address' : IDL.Text,
  });
  const ProfessorProfile = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'institution' : IDL.Text,
    'name' : IDL.Text,
    'department' : IDL.Text,
    'location' : IDL.Text,
  });
  const Publication = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Text,
    'year' : IDL.Nat,
    'publication' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateStudent' : IDL.Func([Student], [], []),
    'addResearchInterest' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getProfessorProfile' : IDL.Func([], [ProfessorProfile], ['query']),
    'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
    'getResearchInterests' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMaintenanceMode' : IDL.Func([], [IDL.Bool], ['query']),
    'removePublication' : IDL.Func([IDL.Text], [], []),
    'removeResearchInterest' : IDL.Func([IDL.Text], [], []),
    'removeStudent' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMaintenanceMode' : IDL.Func([IDL.Bool], [], []),
    'updatePublication' : IDL.Func([Publication], [], []),
  });
};

export const init = ({ IDL }) => { return []; };